name: Sync branches
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - staging
      - develop
    types: [opened]

permissions:
  # Needed to read branches
  contents: read
  # Needed to create PR's
  pull-requests: write

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
            node-version: 'latest'
      - name: Opening develop pull request
        id: pull_develop
        uses: jdtx0/branch-sync@v1.5.1
        if: github.event.ref != 'refs/heads/develop'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_AUTO_MERGE_METHOD: "merge"
          FROM_BRANCH: "main"
          TO_BRANCH: "develop"
          LABELS: '["automerge"]'
      - name: Opening staging pull request
        id: pull_staging
        uses: jdtx0/branch-sync@v1.5.1
        if: github.event.ref != 'refs/heads/staging'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_AUTO_MERGE_METHOD: "merge"
          FROM_BRANCH: "main"
          TO_BRANCH: "staging"
          LABELS: '["automerge"]'
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
