name: Sync main to staging and develop

on: 
  push: 
    branches:
      - main 

jobs: 
  branch-sync:
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4     
        with: 
          fetch-depth: 0 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up git 
        run: | 
          git config --global user.name 'Bot'
          git config --global user.email 'both@yieldguild.games'
      - name: Push changes to staging when main is updated
        if: github.ref == 'refs/heads/main'
        run: | 
          git fetch origin 
          git checkout staging 
          git merge main -X theirs 
          git push origin staging

      - name: Push Changes to develop when main is updated
        if: github.ref == 'refs/heads/main'
        run: |
          git fetch origin
          git checkout develop
          git merge main -X theirs
          git push origin develop
