name: Sync master to staging

on: 
  push: 
    branches:
      - main 

jobs: 
  branch-sync:
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4     
        with: 
          fetch-depth: 0 

      - name: Set up git 
        run: | 
          git config --global user.name 'Felix'
          git config --global user.email 'felix.huynh@yieldguild.games'     
          
      - name: Push changes to staging when main is updated
        if: github.ref == 'refs/heads/main'
        run: | 
          git fetch origin 
          git checkout staging 
          git merge main -X theirs 
          git push origin staging
